name: reversi_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^2.0.0
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  very_good_analysis: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/background.jpg
